name: flutter_app_name
description: A package that makes it easy to set your flutter app launcher name. 
version: 0.1.2
maintainer: Fabio Tea (@f4bio) 
homepage: https://github.com/f4bio/flutter_app_name
original_project: https://github.com/f-prime/flutter_app_name

dependencies:
  yaml: ^3.1.2
  xml: ^6.4.2
  rename: ^2.1.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dev_dependencies:
  test: ^1.24.6

flutter_app_name:
  name: "Flutter App Name"
